/*
* Thanks to https://dev.to/luizcalaca/autogenerated-documentation-api-with-openapi-and-swagger-for-nodejs-and-express-31g9
*/
const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
      title: 'My API',
      description: 'Description',
    },
    host: null,
    schemes: [],
  };

const outputFile = './swagger_output.json';
const endpointsFiles = ['config/route'];

swaggerAutogen(outputFile, endpointsFiles, doc);