containers:
  - name: frontend

serviceAccount:
  create: true
  name: "frontend"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: test-frontend.domain.com
      paths: ["/"]