{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sample-app.name" .}}-config
  namespace: {{.Release.Namespace}}
  labels:
    "app.kubernetes.io/name": '{{ template "sample-app.name" .}}'
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
data:
{{ toYaml .Values.config | indent 2 }}
{{- end }}
