apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- if .Values.updateStrategy }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-app.selectorLabels" . | nindent 8 }}
      annotations:
        timestamp: "{{ date "20060102150405" now }}"
{{- if .Values.annotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:

      {{- range .Values.containers }}
        - name: {{ .name }}
          image: {{ $.Values.image.registry }}/{{ $.Values.image.name }}:{{ .name }}-{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}

          volumeMounts:
          {{- if .volumeMounts }}
          {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
          {{- end }}
          {{- end }}

          {{- if $.Values.config }}
          {{- range $.Values.config }}
          {{- if .mountPath }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .name }}
          {{- end }}
          {{- end }}
          {{- end }}




          {{- if $.Values.env }}
          env:
            {{- toYaml $.Values.env | nindent 12 }}
          {{- end }}


          {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}

          {{- if .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}

          {{- if .startupProbe }}
          startupProbe:
            {{- toYaml .startupProbe | nindent 12 }}
          {{- end }}

      {{- end }}


          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }} 
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:

      {{- if .Values.persistence }}
      {{- range .Values.persistence.volumes }}
        - {{ . | toYaml | nindent 10 -}}
      {{- end }}
      {{- end }}

      {{- if .Values.config }}
      {{- range .Values.config }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
      {{- end }}
      {{- end }}