{{- if (.Values.route) -}}
{{- $fullName := include "sample-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  path: /
  to:
    kind: Service
    name: {{ include "sample-app.fullname" . }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: Edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}